---
- name: Install Clickhouse
  hosts: clickhouse
  become: true
  handlers:
    - name: Start clickhouse service
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
  tasks:
    - block:
        - name: Get clickhouse distrib
          ansible.builtin.apt:
            deb: "https://packages.clickhouse.com/deb/pool/main/c/clickhouse-common-static/clickhouse-common-static_{{ clickhouse_version }}_amd64.deb"
        - name: Get clickhouse distrib
          ansible.builtin.apt:
            deb: "https://packages.clickhouse.com/deb/pool/main/c/{{ item }}/{{ item }}_{{ clickhouse_version }}_all.deb"
          with_items: "{{ clickhouse_packages }}"
      rescue:
        - name: Get clickhouse distrib
          ansible.builtin.apt:
            deb: "https://packages.clickhouse.com/deb/pool/main/c/clickhouse-common-static/clickhouse-common-static_{{ clickhouse_version }}_amd64.deb"

      notify: Start clickhouse service
    - name: Flush handlers
      ansible.builtin.meta: flush_handlers
    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc !=82
      changed_when: create_db.rc == 0

- name: Install Vector
  hosts: vector
  become: true
  handlers:
    - name: Config vector
      ansible.builtin.shell:
        cmd: "vector --config {{ vector_dir }}/config/vector.toml >/dev/null 2>&1 &"

  tasks:
    - name: Check if vector dir exists
      ansible.builtin.stat: path="{{ vector_dir }}"
      register: vector_dir_stat

    - name: Create dir for vector installation
      ansible.builtin.file:
        path: "{{ vector_dir }}"
        state: directory
        owner: "root"
        group: "root"
        mode: '0755'
      when: not vector_dir_stat.stat.exists

    - name: Clean up dir for vector installation
      ansible.builtin.file:
        state: absent
        path: "{{ vector_dir }}/"
      when: vector_dir_stat.stat.exists

    - name: Get vector distrib
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz"
        dest: "{{ vector_dir }}/vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz"
        mode: '0644'

    - name: Extract archive
      ansible.builtin.unarchive:
        src: "{{ vector_dir }}/vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz"
        dest: "{{ vector_dir }}"
        copy: false # if true ansible would try to copy the archive from controller

    - name: Check if archive folder is empty
      ansible.builtin.stat: path="{{ vector_dir }}/vector-x86_64-unknown-linux-musl/"
      register: archive_dir_stat

    - name: Move to vector_dir
      ansible.builtin.shell:
        cmd: 'mv {{ vector_dir }}/vector-x86_64-unknown-linux-musl/* /opt/vector/'
      when: archive_dir_stat

    - name: Recursively remove vector archive directory
      ansible.builtin.file:
        path: /opt/vector/vector-x86_64-unknown-linux-musl
        state: absent
      when: archive_dir_stat

    # this task do not pass lint test but it depends on var value which can be changed every new playbook run
    - name: Add another bin dir to system-wide $PATH
      ansible.builtin.shell:
        cmd: 'echo "PATH=$PATH:{{ vector_dir }}" > /etc/profile.d/vector-path.sh'

    - name: Check if sym link for vector exists in /usr/bin
      ansible.builtin.stat: path="/usr/bin/vector"
      register: vector_bin_stat

    - name: Replace sym link for vector
      block:
        - name: Delete old vector symlink in /usr/bin
          ansible.builtin.file:
            path: "/usr/bin/vector"
            state: absent

        - name: Add vector symlink to /usr/bin
          ansible.builtin.file:
            src: "{{ vector_dir }}/bin/vector"
            dest: "/usr/bin/vector"
            state: link

      when: vector_bin_stat

    - name: Add vector symlink to /usr/bin
      ansible.builtin.file:
        src: "{{ vector_dir }}/bin/vector"
        dest: "/usr/bin/vector"
        state: link
      when: not vector_bin_stat

- name: Install Lighthouse
  hosts: lighthouse
  become: true
  handlers:
    - name: Start nginx
      ansible.builtin.service:
        name: nginx
        state: restarted

  tasks:
    - name: Clone Lighthose git repository
      ansible.builtin.git:
        repo: "https://github.com/VKCOM/lighthouse.git"
        dest: "{{ lighthouse_dir }}"
        clone: true
        update: true

    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: Recursively remove /var/www/html
      ansible.builtin.file:
        path: /var/www/html
        state: absent

    - name: Create symlink for NGINX to open Lighthouse
      ansible.builtin.file:
        src: "{{ lighthouse_dir }}"
        dest: /var/www/html
        owner: root
        group: root
        mode: '0755'
        state: link
