{
 "title": "separated cpu0",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Node Load aka CPU LA",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1*100", "legendFormat": "CPU LA 1" },
    { "expr": "node_load5*100", "legendFormat": "CPU LA 5" },
    { "expr": "node_load15*100", "legendFormat": "CPU LA 15" },
    {
     "expr": "node_load5 / count by (instance, job) (node_cpu_seconds_total{mode=\"idle\"}) * 100"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "CPU0 Utilization without idle",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{cpu=\"0\",mode=\"iowait\"}[5m])*100\n"
    },
    {
     "expr": "rate(node_cpu_seconds_total{cpu=\"0\",mode=\"irq\"}[5m])*100"
    },
    {
     "expr": "rate(node_cpu_seconds_total{cpu=\"0\",mode=\"nice\"}[5m])*100"
    },
    {
     "expr": "rate(node_cpu_seconds_total{cpu=\"0\",mode=\"softirq\"}[5m])*100"
    },
    {
     "expr": "rate(node_cpu_seconds_total{cpu=\"0\",mode=\"steal\"}[5m])*100"
    },
    {
     "expr": "rate(node_cpu_seconds_total{cpu=\"0\",mode=\"system\"}[5m])*100"
    },
    {
     "expr": "rate(node_cpu_seconds_total{cpu=\"0\",mode=\"user\"}[5m])*100"
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(node_memory_MemFree_bytes[30m]) / 1000000000"
    }
   ]
  },
  {
   "title": "Free space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} / 1000000000"
    }
   ]
  }
 ]
}