resource "local_file" "inventory" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.

    [clickhouse]
    clickhouse01.netology.yc ansible_host=${yandex_compute_instance.clickhouse01.network_interface.0.nat_ip_address} ansible_user=ubuntu

    DOC
  filename = "../inventory/prod.yml"

  depends_on = [
    yandex_compute_instance.clickhouse01,

  ]
}
