---
#  - src: https://github.com/Scandr/clickhouse-role.git
#    scm: git
##    version: "1.11.0"
#    name: clickhouse

  - src: https://github.com/AlexeySetevoi/ansible-clickhouse.git
    scm: git
    version: "1.11.0"
    name: clickhouse-vendor

  - src: https://github.com/Scandr/vector-role.git
    scm: git
    version: "0.0.1"
    name: vector

  - src: https://github.com/Scandr/lighthouse-role.git
    scm: git
    version: "0.0.2"
    name: lighthouse
