resource "local_file" "inventory" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.

  [jenkins_masters]
    jenkins-master01.netology.yc ansible_host=${yandex_compute_instance.jenkins-master01.network_interface.0
.nat_ip_address} ansible_user=centos
  [jenkins_agents]
    jenkins-agent01.netology.yc ansible_host=${yandex_compute_instance.jenkins-agent01.network_interface.0
.nat_ip_address} ansible_user=centos

    DOC
  filename = "../inventory/cicd/hosts.yml"

  depends_on = [
    yandex_compute_instance.jenkins-master01,
    yandex_compute_instance.jenkins-agent01
  ]
}
