

node("myagent"){

    properties([
        parameters([
            booleanParam(name: 'prod_run', defaultValue: false,  description: 'Is it prod deploy?')
        ])
    ])

    stage("Git checkout"){
        git url: 'https://github.com/aragastmatb/example-playbook.git'
    }
    stage("Sample define secret_check"){
        secret_check=true
    }
    stage("Run playbook"){
        if (secret_check){
            if (prod_run){
                sh 'ansible-playbook site.yml -i inventory/prod.yml --check --diff'
            } else {
                sh 'ansible-playbook site.yml -i inventory/prod.yml'
            }
        }
        else{
            echo 'need more action'
        }
        
    }
}