properties([
    parameters([
        booleanParam(defaultValue: 'false', name: 'prod_run', description: 'Is it a prod deployment?')
    ])
])

node("myagent"){
    stage("Git checkout"){
        git url: 'https://github.com/aragastmatb/example-playbook.git'
    }
    stage("Sample define secret_check"){
        secret_check=true
    }
    stage("Run playbook"){
        if (secret_check){
            if (prod_run){
                sh 'ansible-playbook site.yml -i inventory/prod.yml --check --diff'
            } else {
                sh 'ansible-playbook site.yml -i inventory/prod.yml'
            }
        }
        else{
            echo 'need more action'
        }
        
    }
}